### ISSUE TITLE
add support for 1x1 scrambles

### ISSUE THREAD

**Issue by Felk** [SpeedcubeDE/ocs5#6]
These would look like y z x x z' y' x' for example

**Comment by DasNaCl** [comment]
This issue is more related to Methuselah96's Prisma Puzzle Timer than to the OCS itself. As I don't really think that Methuselah96 would appreciate this joke as standard in his repository, I suggest to either discard this or violate Dijkstra and get a bit dirty, by not using Prisma Puzzle Timer's scrambling capability for this.
